services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    volumes:
      - ./docker_data/.postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - app_network

  redis:
    image: redis:8.8-alpine
    container_name: redis
    volumes:
      - ./docker_data/.redis_data:/data
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - app_network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: "1000:1000"
    container_name: zookeeper
    volumes:
      - ./docker_data/.Zookeeper:/var/lib/zookeeper/data
    env_file:
      - ./.env
    environment:
      ZOOKEEPER_CLIENT_PORT: ${KAFKA_ZOOKEEPER_PORT}
    ports:
      - "${KAFKA_ZOOKEEPER_PORT}:${KAFKA_ZOOKEEPER_PORT}"
    healthcheck:
      test: ["CMD", "zookeeper-shell", "localhost:2181", "ls", "/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_network    

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    user: "1000:1000"
    container_name: kafka
    volumes:
      - ./docker_data/.kafka_data:/var/lib/kafka/data
    env_file:
      - ./.env
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${KAFKA_ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_BROKER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_BROKER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - "${KAFKA_BROKER_PORT}:${KAFKA_BROKER_PORT}"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:${KAFKA_BROKER_PORT}", "--version"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app_network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks:
      - app_network

  post:
    build:
      context: .
      dockerfile: services/post/Dockerfile
    dns:
    - 8.8.8.8
    - 1.1.1.1
    container_name: post_service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POST_HTTP_PORT: ${POST_HTTP_PORT}
      GRPC_PORT: ${GRPC_PORT}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKER_HOST: ${KAFKA_BROKER_HOST}
      KAFKA_BROKER_PORT: ${KAFKA_BROKER_PORT}
    ports:
     - "${POST_HTTP_PORT}:${POST_HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app_network

  notification:
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    dns:
    - 8.8.8.8
    - 1.1.1.1
    container_name: notification_service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POST_HTTP_PORT: ${POST_HTTP_PORT}
      GRPC_PORT: ${GRPC_PORT}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKER_HOST: ${KAFKA_BROKER_HOST}
      KAFKA_BROKER_PORT: ${KAFKA_BROKER_PORT}
    ports:
     - "${NOTIFICATION_HTTP_PORT}:${NOTIFICATION_HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app_network
  
  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    dns:
    - 8.8.8.8
    - 1.1.1.1
    container_name: user_service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POST_HTTP_PORT: ${POST_HTTP_PORT}
      HTTP_PORT: ${USER_HTTP_PORT}
      GRPC_PORT: ${GRPC_PORT}
    ports:
     - "${USER_HTTP_PORT}:${USER_HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app_network


networks:
  app_network:
    driver: bridge