// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/user/proto/user.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Request_ID    string                 `protobuf:"bytes,2,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_services_user_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_services_user_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserRequest) GetRequest_ID() string {
	if x != nil {
		return x.Request_ID
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	Request_ID    string                 `protobuf:"bytes,4,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_services_user_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_services_user_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetUserResponse) GetRequest_ID() string {
	if x != nil {
		return x.Request_ID
	}
	return ""
}

var File_services_user_proto_user_proto protoreflect.FileDescriptor

const file_services_user_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/user/proto/user.proto\"H\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"request_ID\x18\x02 \x01(\tR\trequestID\"t\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"request_ID\x18\x04 \x01(\tR\trequestID2;\n" +
	"\vUserService\x12,\n" +
	"\aGetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponseB\bZ\x06/protob\x06proto3"

var (
	file_services_user_proto_user_proto_rawDescOnce sync.Once
	file_services_user_proto_user_proto_rawDescData []byte
)

func file_services_user_proto_user_proto_rawDescGZIP() []byte {
	file_services_user_proto_user_proto_rawDescOnce.Do(func() {
		file_services_user_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_user_proto_user_proto_rawDesc), len(file_services_user_proto_user_proto_rawDesc)))
	})
	return file_services_user_proto_user_proto_rawDescData
}

var file_services_user_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_user_proto_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),  // 0: GetUserRequest
	(*GetUserResponse)(nil), // 1: GetUserResponse
}
var file_services_user_proto_user_proto_depIdxs = []int32{
	0, // 0: UserService.GetUser:input_type -> GetUserRequest
	1, // 1: UserService.GetUser:output_type -> GetUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_user_proto_user_proto_init() }
func file_services_user_proto_user_proto_init() {
	if File_services_user_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_user_proto_user_proto_rawDesc), len(file_services_user_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_proto_user_proto_goTypes,
		DependencyIndexes: file_services_user_proto_user_proto_depIdxs,
		MessageInfos:      file_services_user_proto_user_proto_msgTypes,
	}.Build()
	File_services_user_proto_user_proto = out.File
	file_services_user_proto_user_proto_goTypes = nil
	file_services_user_proto_user_proto_depIdxs = nil
}
